// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OglasURIS.Data;

#nullable disable

namespace OglasURIS.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OglasURIS.Models.Oglas", b =>
                {
                    b.Property<int>("OglasId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OglasId"));

                    b.Property<DateTime>("DatumObjave")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("JavnoNadmetanjeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ObjavljenUListuId")
                        .HasColumnType("int");

                    b.Property<string>("OpisOglasa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RokZaZalbu")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SluzbeniListId")
                        .HasColumnType("int");

                    b.HasKey("OglasId");

                    b.HasIndex("SluzbeniListId");

                    b.ToTable("Oglasi");
                });

            modelBuilder.Entity("OglasURIS.Models.SluzbeniList", b =>
                {
                    b.Property<int>("SluzbeniListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SluzbeniListId"));

                    b.Property<int>("BrojLista")
                        .HasColumnType("int");

                    b.Property<DateTime>("DatumIzdanja")
                        .HasColumnType("datetime2");

                    b.HasKey("SluzbeniListId");

                    b.ToTable("SluzbeniListovi");
                });

            modelBuilder.Entity("OglasURIS.Models.Oglas", b =>
                {
                    b.HasOne("OglasURIS.Models.SluzbeniList", null)
                        .WithMany("ListaOglasa")
                        .HasForeignKey("SluzbeniListId");
                });

            modelBuilder.Entity("OglasURIS.Models.SluzbeniList", b =>
                {
                    b.Navigation("ListaOglasa");
                });
#pragma warning restore 612, 618
        }
    }
}
